spring:
  application:
    name: mrumbl-backend

  datasource:
      # MySQL
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mrumbl_db?&serverTimezone=Asia/Seoul
      username: developer
      password: R8$M!xP4

  redis:
    host: localhost
    port: 6379
    timeout: 2000
#    password:

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    # 영속성의 유지를 Controller 와 View 까지 가져갈 것인가? (읽기에 대해서만..)
    open-in-view: false

  mail:
    host: smtp.gmail.com        # SMTP 서버 호스트
    port: 587                   # SMTP 서버 포트
    username: mk.app.info1      # SMTP 서버 로그인 아이디
    password: mlqsnieyfzfgifij  # SMTP 서버 로그인 비밀번호
    properties:
      mail:
        smtp:
          auth: true            # 사용자 인증 시도 여부
          starttls:
            enable: true        # starttls 활성화 여부

jwt:
  secret: dmdlbl9zZWNyZXRfMDIwMV92Z2VuX3NlY3JldF8wMjAxdmdlbl9zZWNyZXRfMDIwMV92Z2VuX3NlY3JldF8wMjAxdmdlbl9zZWNyZXRfMDIwMV92Z2VuX3NlY3JldF8wMjAx
  access_token_expiration: 3600000   # 1 hour (ms)
  refresh_token_expiration: 1209600000 # 14 days (ms)
